### ISSUE TITLE
undefined method `preference' for Spree::Recurring(Table doesn't exist)

### ISSUE THREAD

**Issue by dpmccabe** [vinsol/spree-account-recurring#6]
I get the following error when trying to run the install generator:
https://gist.github.com/dpmccabe/c53aeecc2b4c7b23e6c8

I'm using the 2-3-stable branch of all the Spree gems on a Rails 4.1.4 app with MRI 2.1.2 on a newly-created app. Is this a versioning issue?

**Comment by Eventect** [comment]
+1, there is already a pull request on the queue (I did not tested it).

**Comment by funkdified** [comment]
+1

**Comment by Qubaish** [comment]
+1 same error

**Comment by priyank-gupta** [comment]
New version is released for spree 2-3-stable.
Branch: 2-3-stable
version: 1.2.x

**Comment by priyank-gupta** [comment]
@aaronzdavis  Also released support for 2.4.
Branch: 2-4-stable
version: 1.3.x

**Comment by siddharth28** [comment]
@priyank-gupta i think we can close this issue.
